### ISSUE TITLE
배포 QA

### ISSUE THREAD

**Issue by dayannne** [dayannne/My-Walk-Log#16]
### 📝 To-do
- 회원가입/로그인
    - [ ]  카카오 로그인 잠시 비활성화 하기
    - [ ]  주소 입력 변경 → 내 동네 설정
    - [ ]  로그인 후 feed 페이지로 이동
- 프로필 페이지
    - [ ]  프로필 페이지 이동 시 에러
- 피드 페이지
    - [ ]  ‘요즘 뜨는’ 추가
- 산책 장소(검색-결과) 페이지
    - [ ]  검색 결과 없을 때 없음 페이지 반환
    - [ ]  새로고침 했을 때 장소결과 유지
    - [ ]  현재 내 위치로 이동 기능 추가
    - [ ]  모달 X 버튼 수정
    - [ ]  현재 위치에서 재검색/카테고리 검색 시에는 영역 변경 금지
    - [ ]  리뷰/일기/찜/사진 보여주고 싶어
- 산책 장소 상세 페이지
    - [ ]  (링크로 이동 시 기본 레이아웃에서 보이기)
     예시 https://map.naver.com/p/entry/place/36142768?placePath=%2Fhome&c=15.00,0,0,0,dh
    - [ ]  리뷰 폼
    - [ ]  리뷰 / 일기 페이지 각각 api 요청으로 관리 → 좋아요 후 refetch 시 너무 오래걸림
    - [ ]  공유 버튼 클릭 시 복사 url 변경
- 산책로 페이지
    - [ ]  검색 결과 없을 때 없음 페이지 반환
    - [ ]  산책로 모달 스크롤 내용 부분만 되도록 수정
    - [ ]  현재 위치 내 검색
        - 현재 boundary 값 가져오기
        - 산책로 DB에서 해당 산책로에 해당하는 거 필터링
- 전체
    - [ ]  스켈레톤 추가
    - [ ]  로딩 컴포넌트 적용 (3개가 움직임)
    - [ ]  any 로 한거 다 타입 정의하기
    - [ ]  좋아요 같은 버튼 로그인 상태에서만 가능하게 수정 (로그인 해야 가능합니다 -> 로그인 페이지 이동)
    - [ ]  Header 화살표 높이 가운데 안맞음
