### ISSUE TITLE
SEO 최적화

### ISSUE THREAD

**Issue by dayannne** [dayannne/My-Walk-Log#18]
### 📝 To-do
- [ ] Metadata 설정하기
- [ ] Sitemap 생성하기
- [ ] robot.txt 생성하기
- [ ] 구글에 사이트 등록 
- [ ] 네이버에 사이트 등록
