### ISSUE TITLE
검색 

### ISSUE THREAD

**Issue by dayannne** [dayannne/My-Walk-Log#2]
## 🌟 검색
카카오맵 api 를 활용해 지도 레이아웃 구현하기
### 📝 To-do
- [x] 키워드로 검색해 장소목록 불러오기
- [x] 검색 목록 산책 가능 장소 기준 필터링
- [x] 검색 결과 장소 마커 / 마커 인포윈도우 표시하기
  - 마커 호버 시 마커 인포윈도우 띄우기 -> 커스텀 오버레이로 구현
  - 마커 / 마커 인포윈도우 클릭 시 해당 마커를 중심으로 지도 이동
  - 마커 인포윈도우 시 장소 상세 페이지 불러오기
- [x] 마커 클러스터러 구현
  - 클릭할 때마다 zoomlevel 1씩 확대   
- [x] 위치 이동 시 재검색
- [x] 카테고리 버튼으로 검색 구현 (공원, 하천 등)
 
### Detail
- 키워드로 검색해 장소목록 불러오기
1차 키워드 검색 후 아래에서 `여행` + `(키워드)` 필터링
    1. `도보여행`, `둘레길`
        
        ```jsx
        
            "category_group_code": "AT4",
            "category_group_name": "관광명소",
            "category_name": "여행 \u003e 관광,명소 \u003e도보여행",
            "place_name": "경춘선숲길",
        },
        ```
        
        ```jsx
        {
            "category_group_code": "AT4",
            "category_group_name": "관광명소",
            "category_name": "여행 \u003e 관광,명소 \u003e 도보여행 \u003e 둘레길",
            "place_name": "서울둘레길 3코스 하늘을 품은 포근한 숲길",
        },
        ```
        
    2. `하천`
        
        ```json
        {
            "category_group_code": "",
            "category_group_name": "",
            "category_name": "여행 \u003e 관광,명소 \u003e 하천",
            "place_name": "중랑천",
        },
        ```
        
    3. `공원`, `도시근린공원`, `국립공원`, `도립공원`
        
        ```json
        {
            "category_group_code": "",
            "category_group_name": "",
            "category_name": "여행 \u003e 공원"
            "place_name": "수인선하늘숲길",
        },
        ```
        
    4. `산`
    5. `오름`
