### ISSUE TITLE
route 설정

### ISSUE THREAD

**Issue by dayannne** [dayannne/My-Walk-Log#3]
## 🌟 route 설정
route 설정을 통해 검색& 지도 페이지 / 로그인 회원가입 페이지를 분리하는 작업 (+네비게이션 바)
### 📝 To-do
- [x] navigation bar 생성
- [x] 초기 경로 `/place`로 세팅
- [x] app route 폴더구조 설정 (`place` - 장소, `trail` - 산책로)
- [x] 레이아웃 변경 -> search 구현 부분(Searchform, SearchResult) `place` 경로 layout으로 이동
