### ISSUE TITLE
장소 목록, 상세

### ISSUE THREAD

**Issue by dayannne** [dayannne/My-Walk-Log#5]
### 📝 To-do
- [x] 장소 좋아요/취소 구현
- [x] 장소 검색 시 DB에 장소 목록, 장소 상세 데이터 생성 로직 구현 6363d4f
#### 장소 목록
- [x] 장소 목록 스타일링 cc21aa8

#### 장소 상세
- [x] 장소 상세 페이지 스타일링
  - [x] 슬라이드 애니메이션으로 장소 상세 페이지 생성
