### ISSUE TITLE
검색 기능 보완

### ISSUE THREAD

**Issue by dayannne** [dayannne/My-Walk-Log#6]
### 📝 To-do
- [x] 검색 엔터 쳐도 작동되도록
- [x] 기본 검색을 현재 위치 기준 -> 전체로 변경
- [x] 지도 이동 시 '현재 위치에서 재검색'으로 현재 위치 기준 검색
- [x] 커스텀 오버레이 클릭시 상세페이지 불러오기
- [x] 클러스터링러 스타일링 수정 ('+개수' 함께 표시)
