### ISSUE TITLE
마이 프로필

### ISSUE THREAD

**Issue by dayannne** [dayannne/My-Walk-Log#8]
### 📝 To-do
- [x] 스키마 수정
- [x] 마이프로필 페이지 디자인
- [x] 마이프로필 정보 받아오기 API 구현
- [x] 일기 작성 폼으로 이동시키기
